### ISSUE TITLE
Opting in and out of cookies

### ISSUE THREAD

**Issue by mgearon-gds** [alphagov/platforms-product-page#3]
**User story**
As a user I want to be able to opt-in or out of cookies either on the cookie banner or on the cookies page at any time. So that I can control what data I share with Government Digital Service and Google.

**Acceptance criteria** 

- [ ] Show the cookie banner if the user has not set their cookie preferences
- [ ] By default the GTM tag should **not** be active if the user has not set their preference
- [ ] If the user clicks "accept analytics cookies" in the cookie banner then hide the banner and enable the GTM tag. The tag should fire on every return visit going forward.
- [ ] If the user clicks "reject analytics cookies" in the cookie banner then hide the banner and continue with the GTM tag not being active
- [ ] If cookies are rejected then hide the banner for up to 30 days
- [ ] If the user clicks "View cookies" in the banner then go to the cookies page (https://platforms.service.gov.uk/help/cookies.html)
- [ ] On the cookies page there should be 2 radio options, one option which says "Use cookies that measure my website use" and the other that says "Do not use cookies that measure my website use" (following the pattern on GOV.UK https://www.gov.uk/help/cookies)
- [ ] If the user has already set their preferences then the correct radio button should be selected
- [ ] If the user has not set their preference then both radio buttons should be in an empty state
- [ ] The user can change their choice of if they are opted-in or opted-out and then they can press a button which says "Save changes"
- [ ] On change of preference the GTM tag should be enabled/disabled depending on the change

**Comment by kr8n3r** [comment]
@mgearon-gds 
_If cookies are rejected then hide the banner for up to 30 days_
In general, none of GDS/DSP frontend estates do this. We set the cookie with a 1 year validity regardless of the preference set.

If the team would still like to set the 30 day limit, I'll work to extend the cookie policy objecy with a created date and then in the initial check extent to work out 30 days since that date.

For the cookies page form, I have gone with what's described on https://design-system.service.gov.uk/patterns/cookies-page/ and hot what gov.uk says.

If required, I can amend the working  to says Use cookies that measure my website use" and the other that says "Do not use cookies that measure my website use"

**Comment by mgearon-gds** [comment]
@kr8n3r let's go with 1 year validity to match other frontend estates please. Happy to go with what has been described on the cookies page.
